[package]
name = "yarrun"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ['canvas'] }
nucleo-matcher = { version = "0.3.1" }
freedesktop_entry_parser = "1.3.0"
rayon = "1.10.0"
